info:
  title: 狼的站点
  subtitle: 记录没用的东西
  author: 狼(o0kam1)
  url: https://o0kam1.dev

defaults:
  avatar: /images/avatar.png

global:
  single_page: false
  website_counter:
    enable: true
    url: "about:blank"
  preloader:
    enable: false
  fonts:
    chinese:
      enable: true
      family: 'Noto Sans SC'
      url: https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@100..900&display=swap
    english:
      enable: true
      family: 'Noto Sans'
      url: https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wdth,wght@0,62.5..100,100..900;1,62.5..100,100..900&display=swap
    title:
      enable: true
      family: 'Noto Sans SC'
#      url: https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@100..900&display=swap
  scroll_progress:
    bar: true
    percentage: false
  side_tools:
    gear_rotation: false

home_banner:
  social_links:
    enable: true
    links:
      github: https://github.com/duzhaokun123
      twitter: https://twitter.com/duzhaokun123
      bilibili: https://space.bilibili.com/174438027
      zhihu: https://www.zhihu.com/people/du-zhao-kun-92
  title: 狼的站点
  subtitle:
    text: ['Loading...']
    loop: false
  style: fixed
  image:
    light: /img/default.png
    dark: /img/default.png

navbar:
  color:
    left: 'var(--background-color-transparent-80)'
    right: 'var(--background-color-transparent-80)'
    transparency:
  links:
    Home:
      path: /
      icon: fa-regular fa-house
    Tools:
      path: /tools
      icon: fa-regular fa-toolbox
    Donate:
      path: /donate
      icon: fa-regular fa-hand-holding-heart

comment:
  enable: false

footer:
  runtime: false
  icon: ""

cdn:
  enable: true
  provider: jsdelivr

articles:
  copyright:
    default: cc_by_sa
  code_block:
    style: simple
    font:
      enable: true
      family: 'Fira Code'
      url: https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap
  author_label:
    enable: false
  code_blockhighlight_theme:
    light: atom-one-light
    dark: atom-one-dark
  word_count:
    min2read: false
  lazyload: false

colors:
  default_mode: dark
  primary: '#B9887D'

inject:
  enable: true
  head:
    - |
      <style>
        .markdown-body img {
          max-height: 80vh;
          width: auto;
        }
      </style>
  footer:
    - |
      <div style="
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
      " onclick="try{zaraz.showConsentModal()}catch(e){alert('不可用')}">
        <img src="https://r2.o0kam1.dev/Privacyoptions.svg" style="height: 15px" alt="Cookie Options">
        &nbsp;&nbsp;
        <a href="javascript:void(0);">Cookie 选项</a>
      </div>